pipeline {
    agent any

    parameters {
        booleanParam(name: 'TERRAFORM_PLAN', defaultValue: false, description: 'Run Terraform Plan')
        booleanParam(name: 'TERRAFORM_APPLY', defaultValue: false, description: 'Run Terraform Apply')
        booleanParam(name: 'TERRAFORM_DESTROY', defaultValue: false, description: 'Run Terraform Destroy')
    }

    stages {
        stage('CLone Repository') {
            steps {

                // Clean workspace before cloning
                deleteDir() 
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/Piyush-patil21/DevOps.git'
            }
        }

        stage ('Directory check') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Initialize') {
            
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds-piyush']]){
                    dir('Terraform-AWS') {
                        sh 'pwd'
                        sh 'terraform init'
                        sh 'sleep 10'
                        sh 'terraform fmt'
                        sh 'terraform validate'

                    }
                }

            }
        }

        stage('Plan') {

            steps {
                script {
                    if (params.TERRAFORM_PLAN) {
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds-piyush']]){
                            dir('Terraform-AWS') {
                                sh 'terraform plan'
                                echo 'Planning...'
                            }
                        }
                    } else {
                        echo 'Skipping Terraform Plan...'
                    }
                }

            }
        }

        stage('Apply') {
            
            steps {
                script {
                    if (params.TERRAFORM_APPLY) {
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds-piyush']]){
                            dir('Terraform-AWS') {
                                sh 'terraform apply -auto-approve'
                                echo 'Applying...'
                            }
                        }
                    } else {
                        echo 'Skipping Terraform Apply...'
                    }
                }

            }
        }  

        stage('Destroy') {
            
            steps {
                script  {   
                    if (params.TERRAFORM_DESTROY) {
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds-piyush']]){
                            dir('Terraform-AWS') {
                                sh 'terraform destroy'
                                echo 'Destroying...'
                            }
                        }
                    } else {
                        echo 'Skipping Terraform Destroy'
                    }
                }
            }
        }
    }

} 